### ISSUE TITLE
some remarks

### ISSUE THREAD

**Issue by jabbalaci** [icyphox/nicy#1]
First of all, thanks for this project. Using this little framework, I could build my own ZSH theme in Nim. My modified `functions.nim` is [here](https://github.com/jabbalaci/jabbas-zsh-settings/blob/master/.zsh/themes/jabba_nim/functions.nim). I have some remarks:
* You could turn some `let`s to `const`s.
* In `tilde()`, `path.replace(home, "~/")` will replace all occurrences of `home`, not just the first one. I had a folder `/home/jabba/Dropbox/home/jabba/etc`, and it appeared as `~/Dropbox~/etc`.
* `git symbolic-ref --short -q HEAD` returns the name of the branch
* `host()` could be simplified as `result = execProcess("hostname")`

**Comment by icyphox** [comment]
Hey,
Thanks for these. I'm still learning Nim so bear with me :)

First off, does `git symbolic-ref --short -q HEAD` give you the commit hash if you're in a ‘detached HEAD’ state? If yes, then it's a good replacement. 

Secondly, would you mind shooting a PR for the other changes? I'm a bit bogged down with school and exams :/

Thanks again!

**Comment by icyphox** [comment]
Also, with regard to the `tilde()` proc, I’m not able to replicate what you’re saying. 
![tilde](https://user-images.githubusercontent.com/17672379/48658973-6534dc80-ea70-11e8-834c-9d81c5e985af.png)

I don’t see it replacing all occurrences of `home`.

**Comment by jabbalaci** [comment]
It replaces your HOME, which is "/home/icy" in your case. In your home folder create for instance "work/home/icy/hello" and enter it.

**Comment by icyphox** [comment]
Thanks! Fixed `tilde()` and credited you in the code :)

**Comment by jabbalaci** [comment]
Great! Then no PR is needed from me :)
