### ISSUE TITLE
Command return code?

### ISSUE THREAD

**Issue by codic12** [icyphox/nicy#12]
Is there a way to use the API to get the return code of the command (would a getenv on "?" work, because of $?)?
I'd like to do this for my fork of this amazing prompt: https://github.com/codic12/nzsh

**Comment by codic12** [comment]
I found the returnCondition proc and template, if this is what I want, can you show an example of how to use it?

**Comment by icyphox** [comment]
> I found the returnCondition proc and template, if this is what I want, can you show an example of how to use it?

This is indeed what you want. The usage is fairly simple, you can pass
it a string or a proc, and it should format it like so:
    
    %(?{delimiter}{ok}{delimiter}{ng})

This is a bit hard-coded, but I didn't write it, heh. You should be able
to rewrite this to suit your needs.

**Comment by codic12** [comment]
Ah okay. I'm not sure what `ng` represents though... could you show an example of how to call it? Sorry, I'm new to Nim :p

**Comment by icyphox** [comment]
codic12 <notifications@github.com> wrote:

> Ah okay. I'm not sure what `ng` represents though...

"not good", I assume?

**Comment by codic12** [comment]
Thanks! Sadly, I'm running into a small issue.
I have
```nim
var rc = returnCondition("ok", "ng")
```
Echoing `rc` gives me ok with a good exit code and ng with a bad exit code. However, `rc.strip() == "ng"` is false even when there's a nonzero exit code, and `rc.strip() == "ok"` is false even when there's an exit code of 0. Therefore I can't make checks against it. Hmm

**Comment by ghost** [comment]
@codic12 as far as I can see nicy doesn't check the return code itself at all - it just emits special strings which ZSH knows how to handle (e.g. for return codes)

**Comment by xyb** [comment]
@codic12 As prompt app you can not get the exit code of the last command unless passing the `$?` through arguments. I have done this in my nicy fork and you may want to check:

https://github.com/xyb/nicy/blob/5986c137ac9bf7041b61dd8c6c2812972674fbcb/nicyprompt.zsh#L19-L21

**Comment by codic12** [comment]
thanks, that does the trick! :-)
