### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by juancarlospaco** [icyphox/nicy#4]
https://github.com/icyphox/nicy#quick-start

- `autolaod` should say `autoload`.

:slightly_smiling_face:

**Comment by icyphox** [comment]
Oh god. I'm _terrible_ at this.

**Comment by juancarlospaco** [comment]
Thanks @icyphox :grey_exclamation: The project rocks :smiley:

**Comment by icyphox** [comment]
Thanks! Share it with fellow zsh users, if you don’t mind :)
