### ISSUE TITLE
`echo` problem

### ISSUE THREAD

**Issue by narimiran** [icyphox/nicy#8]
```
nicy.nim(19, 8) Error: ambiguous call; 
  both system.echo(x: varargs[typed]) [declared in C:\projects\nim\lib\system.nim(3451, 8)]
  and functions.echo(s: cstring) [declared in C:\projects\nim\pkgstemp\nicy\src\nicypkg\functions.nim(133, 6)]
  match for: (string)
```

I'm guessing it has to do with #7, which stated "* Add an echo that uses C printf directly".

cc @juancarlospaco

**Comment by icyphox** [comment]
Oh yikes, yeah. I don't use nicy anymore, so I assumed @juancarlospaco
had tested it out. I should probably rollback.

-- 
Anirudh Oppiliappan
0x8A93F96F78C5D4C4

**Comment by icyphox** [comment]
@juancarlospaco, I've reverted your changes for now and pushed a hotfix version bump. You may re-create a PR with the other changes.

**Comment by juancarlospaco** [comment]
Technically this is not a bug, but a feature of the language, you should use full name, 
or a template to a call with full name, or rename the proc on your code.

But PR is ready, or feel free to rename it to whatever you think fits the rest of the API.

**Comment by icyphox** [comment]
@juancarlospaco Done. Thanks!
